goalsapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resource :session, only: [:new, :create, :destroy]
end

goalsapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

goalsapp/app/models/user.rb
class User < ApplicationRecord
    validates :username, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    after_initialize :ensure_session_token
    attr_reader :password

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        if user && user.is_password?(password)
            user
        else
            nil
        end
    end

    def is_password?(password)
        password_object = BCrypt::Password.new(self.password_digest)
        password_object.is_password?(password)
    end

    def generate_session_token
        SecureRandom::urlsafe_base64
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def ensure_session_token
        self.session_token ||= generate_session_token
    end

    def reset_session_token!
        self.session_token = generate_session_token
        self.save!
        self.session_token
    end


end

# fig vaper celll

goalsapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  helper_method :current_user, :logged_in?

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logged_out
    current_user.reset_session_token! if logged_in?
    session[:session_token] = nil
    current_user = nil
  end

  def current_user
    @user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def require_logged_out
    redirect_to new_session_url if logged_in?
  end
end

goalsapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # before_action :require_logged_out, only: [:new, :create]
  # before_action :require_logged_in, only: [:destroy]

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username],
    params[:user][:password])
    if @user 
      login_user!(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def destroy
    logged_out
    redirect_to new_session_url
  end
end

goalsapp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      flash.now[:message] = "Successfully logged in!"
      render :show
    else
      flash.now[:error] = "Invalid"
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

goalsapp/app/helpers/application_helper.rb
module ApplicationHelper
end

goalsapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goalsapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in?  %>
      <form action="<%= session_url %>" method="POST">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" value="Logout">
    </form>
    <% else %>
      <a href = "<%= new_user_url %>"> Sign Up </a>
      <a href = "<%= new_session_url %>"> Log in</a>
    <% end  %>
    <%= yield %>
  </body>
</html>

goalsapp/app/views/users/new.html.erb
<h1> Create new user! </h1>

<form action = "<%= users_url %>", method = 'post'>
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<label for = "username"> Username: </label>
<input type = "text" id = "username" name = user[username]>
<label for = "password"> Password: </label>
<input type = "password" id = "password" name = user[password]>
<button> Submit </button>
</form>

goalsapp/app/views/users/show.html.erb
<h1> <%= "Hello #{current_user.username}" %></h1>